### ISSUE TITLE
Vue3 Support

### ISSUE THREAD

**Issue by mrddter** [motla/vue-document-editor#10]
Hi. This component is **very** interesting.

I'm trying to use Demo.vue page in a blank Vue 3 project. But, I found some issues, probably in the conversion or something like that.

Is compatible or is there an example of how to use it?

**Comment by motla** [comment]
Hi! Thanks :)
I've not tested it under Vue3 yet, but from what I've seen they removed the [$nextTick method used here](https://github.com/motla/vue-document-editor/blob/master/src/DocumentEditor/DocumentEditor.vue#L129). I believe this is the main reason for issues.
I don't have much free time now. If you really need the Vue 3 compatibility and you feel able to debug it, don't hesitate to fork and submit a PR.
Otherwise I can look at it but probably not before this September because I'm really full... sorry.

**Comment by motla** [comment]
Yeah ignore my previous comment about $nextTick, apparently it's still present in v3.
Better check https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes

**Comment by mrddter** [comment]
another point to consider is this
https://v3.vuejs.org/guide/migration/array-refs.html#migration-strategy

**Comment by mrddter** [comment]
I'm testing this, perhaps is a good point to start 🚀 

https://gist.github.com/mrddter/50196b948810b6b4f757ea3fa63099c9

**Comment by mrddter** [comment]
It's working well on vue3. Thanks 👍

**Comment by mrddter** [comment]
It's working well on vue3. Thanks 👍

**Comment by motla** [comment]
Thanks a lot for your help! I'm currently on vacation, I look at it when I'm home 😉

**Comment by motla** [comment]
@mrddter Library is now migrated to Vue3 from v2.0.0, thanks for your help.
