### ISSUE TITLE
Use with tailwindcss

### ISSUE THREAD

**Issue by jiexaspb** [motla/vue-document-editor#19]
I use tailwindcss and I need to specify h1, ol, ul styles, I do it like this in my component:

```
<style>
.editor h1 {
  @apply text-3xl;
}
</style>
```

It works:

![image](https://user-images.githubusercontent.com/4509131/196007971-26bb4159-342b-4c6d-a5ad-f387e062f9c1.png)

But when I press print, the styles are not applied. How can this be fixed?

![image](https://user-images.githubusercontent.com/4509131/196008053-32e36ddf-7c80-4c3a-887c-0031dae83d59.png)

Thanks

**Comment by motla** [comment]
Hello!

When printing, all of the `<body>` content is replaced temporarily by the document itself, with a different stylesheet adapted for printing.

So I would guess that maybe part of your CSS has been located in the `<body>` section and is not kept during the print operation.
Otherwise it could be a style overload but it is less probable.

If this doesn't help, can you provide me a link to your work so I could check what is going wrong?

**Comment by motla** [comment]
Well actually I just checked the `before_print` method and it doesn't take the class nor style into account...
I have to patch it for your use case to work. I can look at it probably tomorrow.

https://github.com/motla/vue-document-editor/blob/80451dcf88eb173e3ca0c84161bc055eb29b277d/src/DocumentEditor/DocumentEditor.vue#L423-L477

**Comment by motla** [comment]
Hi!
It should be fixed in v1.2.8 (Vue2) and v2.0.6 (Vue3).
Please let me know if you still have issues.
