### ISSUE TITLE
Well, dear friends, when will you add pictures, forms, comments and directories

### ISSUE THREAD

**Issue by frontend-qin** [motla/vue-document-editor#20]
**Upload pictures**
 base64 or online upload, or local upload, or ctrl+v upload

**Add Table**
Slide the mouse into rendering n rows and n columns, select and merge cells, add and delete columns and rows, and drag the mouse to adjust the height of rows

**Add a comment**
You can select one or more words for a paragraph of text, or add comments to it by overlapping it

**Implementation document directory**
Document directory similar to Word

**Add Referenced Paragraph**
Click the pop-up window and select a paragraph of text to render to the last out of focus position of the editor

**Comment by motla** [comment]
Hello
You definitely have great ideas, unfortunately I won't develop it because I don't need it.
I'm sorry.
Don't hesitate to fork the project and hack it with your own code. If you are pretty proud of your work, you can then make a pull request so I can merge it to the main project. It's how open-source works.
Good luck!

**Comment by frontend-qin** [comment]
yes,i do
