### ISSUE TITLE
There is a page overwriting problem in paging, and the page does not automatically change

### ISSUE THREAD

**Issue by 1738736002** [motla/vue-document-editor#29]
**Describe the bug**
I ran into the same problem with vue.2.7.14, where the previous page exceeded the part hidden behind the next page.

github：https://github.com/1738736002/vue2-demo
Corresponding to page 7 after the project started.

I have another question, why does my 'Hellowrod' component actually have a lot of content, but only render a page of content, and not automatically create a new page.

**Comment by motla** [comment]
Hi!

Thanks for your interest on the library.

I can't install your template project, because it needs Python configured to build some dependency, and I don't have time to get into this... Please make a minimal example for me, if possible compiled to run directly on the browser. The best way to do this would be to fork my project and just change the document content in Demo.vue by the one which causes issues, then run `npm run build` to compile in the `docs` folder and configure Github Pages to run inside the docs folder.

For your second question, the answer is this library doesn't support multiple pages split on Vue.js templates, simply because I can't modify the content managed dynamically by Vue, otherwise it brakes it. So you have to choose between plain HTML content which splits between multiple pages, or single template pages managed by Vue.js.

I hope it is clearer for you.

Please reopen this issue if you make me a simple demo that I can run without install.
