### ISSUE TITLE
Is that possible with multi-page template?

### ISSUE THREAD

**Issue by DavidSun0403** [motla/vue-document-editor#5]
I use a vue template to create some uneditable fields just like InvoiceTemplate.vue.
But I found that the content template can not larger than one page, so is that possible to have a multi-page template?

**Comment by motla** [comment]
Hi
I didn't manage to make it because Vue controls the content of the div representing the page. If the page overflows and I move the some of its content into the next page, then Vue is lost.
What you can do is
- Manage your template pages number and contents in the level of Demo.vue, not InvoiceTemplate.vue
- Avoid using template pages and instead use `contenteditable="false"` blocks in the HTML content you provide, like shown in the first page of the demo
